author: Raul Jordan
email: rauljordan@alumni.harvard.edu
about: Hi, my name is Raul Jordan - I am a software engineer working on the Ethereum blockchain protocol. I write about distributed systems programming, technology, life, and ideas for how we can create a less zero-sum world.
social_links:
  - url: https://github.com/rauljordan
    icon: github-square
    color: purple
  - url: https://twitter.com/rauljordaneth
    icon: twitter-square
    color: cyan
  - url: https://medium.com/@rauljordan
    icon: medium
    color: red

